### ISSUE TITLE
회원탈퇴 기능 필요

### ISSUE THREAD

**Issue by StarkDuebusy** [StarkDuebusy/DietManager-server#5]
회원 탈퇴 기능 필요

회원 탈퇴 클릭 시 '고객님의 모든 데이터가 삭제되며 영구히 복구할 수 없습니다. 회원탈퇴를 진행하시겠습니까?' 문구와 함께 한번더 물어보고 모두 삭제해야함.

**Comment by StarkDuebusy** [comment]
디비를 살펴보면 user를 기점으로 외래키로 연결되어있어서 user의 로우만 삭제하면 모두 연계casecade로 삭제하게 디비설정을 먼저 세팅해주고.

그 다음에 백엔드 단에서 user만 지우게 하여 간결하게 만들어야함.

**Comment by min950903** [comment]
finisf
